### ISSUE TITLE
Erratic response to built-in traits

### ISSUE THREAD

**Issue by jefhil** [googlesamples/assistant-sdk-nodejs#5]
I have defined a device with all traits except temperature enabled.  when testing, i receive erratic responses for builtin traits. I have defined 2 custom traits that always work. For example, 
> : start
{}
> : start
{}
> : start
{}
> : go to dock
{}
> : start
{
   "deviceAction": {
      "inputs": [
         {
            "context": {
               "locale_language": "en"
            },
            "intent": "action.devices.EXECUTE",
            "payload": {
               "commands": [
                  {
                     "devices": [
                        {
                           "id": "xxxxxxxxxxx"
                        }
                     ],
                     "execution": [
                        {
                           "command": "action.devices.commands.StartStop",
                           "params": {
                              "start": true
                           }
                        }
                     ]
                  }
               ]
            }
         }
      ],
      "requestId": "xxxxxxxxxxxx"
   }
}
Here's the device model definition:

   "deviceModels": [
      {
         "deviceModelId": "xxxxxxx-yyyyyyy",
         "projectId": "xxxxxxxxxxxxxxx",
         "manifest": {
            "manufacturer": "xxx",
            "productName": "xxx"
         },
         "name": "projects/xxxxxxxxxxxxxxx",
         "deviceType": "action.devices.types.LIGHT",
         "traits": [
            "action.devices.traits.Brightness",
            "action.devices.traits.ColorSpectrum",
            "action.devices.traits.ColorTemperature",
            "action.devices.traits.Dock",
            "action.devices.traits.OnOff",
            "action.devices.traits.StartStop"
         ],
         "executionModes": [
            "DIRECT_RESPONSE"
         ],
         "lastUpdatedTime": "2018-10-29T21:29:16.591690742Z"
      }
   ]

Similar behavior happens with turn on/off, go to dock. Color setting  (e.g. set the light to red) never seems to work

**Comment by Fleker** [comment]
Are you setting the model and instance ID in every request? Is there something in the request that changes?

**Comment by jefhil** [comment]
yes I am setting both model and instance id. Nothing changed. These were typed exactly as you see them -- in the same session, one after another.
