### ISSUE TITLE
All data.device_action are null in the response

### ISSUE THREAD

**Issue by GregPeck** [googlesamples/assistant-sdk-nodejs#7]
Hello,

When I ask "Is the light on?", I do not have a textual answer, but I earing for example "The light is off" (via data.audio_out.audio_data)
All data.device_action are null in the response

Did I miss something?

Thanks

**Comment by Fleker** [comment]
The Assistant SDK does not return text for smart home queries. `device_action` is for device actions if that's configured for a project.

**Comment by AllenWu0913** [comment]
I could control smart home device through Assistant SDK, like turn switch on/off.
How could i get smart home device status through other SDK or using Assistant SDK?
