### ISSUE TITLE
How to setup actions.capability.SCREEN_OUTPUT capability

### ISSUE THREAD

**Issue by adambezecny** [googlesamples/assistant-sdk-nodejs#8]
hi,

I was trying to use this sample (and also original code here https://github.com/actions-on-google/actions-on-google-testing-nodejs) for google action which is checking if user's device has actions.capability.SCREEN_OUTPUT capability and if not it will forward to screen enabled device (using conv.ask(new NewSurface({ ...) 

The problem is if (conv.surface.capabilities.has('actions.capability.SCREEN_OUTPUT')) { .. always evaluates to false. I was trying to change the registered device I am using for testing from Light to Phone but it did no help (though I was lazy to regenerate credentials). Any idea what needs to be done so that this sample code is actually working as if with screen enabled device?

thanks,

Adam

**Comment by adambezecny** [comment]
one more update: i did register brand new device, this time Phone from the very beginning and did test using new credentials. result still the same: screen output capability is reported as not being supported.

**Comment by Fleker** [comment]
Setting surface capabilities is not something that is supported in the testing library right now, and it's not available as a setting in the SDK.
