### ISSUE TITLE
Search questions returning 'undefined'

### ISSUE THREAD

**Issue by JamiePoole** [googlesamples/assistant-sdk-nodejs#9]
Hi

I followed all the steps and confirmed it works/communicates by querying "Hello". It also works for definitions/information responses: "What is ...?"

But any 'complex' search queries which DO return results on Assistant on device/App -- return 'undefined'.

For our clients purpose I have ommitted their name but a few examples:

"What is ...?" -- text: "... is a blah blah blah (from Wikipedia)"
"When does ... start?" -- undefined
"Can you take dogs on ..." -- undefined
"How long is the ...?" -- undefined

All the above undefined responses return correct answers on the App follow-up or when asking a Home device.

Is this just not possible with this SDK?

**Comment by Fleker** [comment]
Not every request will return supplemental display text.

**Comment by JamiePoole** [comment]
> Not every request will return supplemental display text.

Thanks for the quick response.

**Comment by HFx6** [comment]
what does that mean exactly? "supplemental display text" is it a limit of the SDK or some account api restrictions? 
things such as "who am i?" return as undefined, which is just a basic text response.

**Comment by Fleker** [comment]
It's an SDK limitation.
